name: Unity - Activate
on:
  workflow_dispatch: {}
jobs:
  testinglicense:
    name: Unity - Activate
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Activate
      uses: game-ci/unity-activate@v2.0.0


